// generates a random name string.

// Often in development one needs a placeholder; a random string.
// If that string can also be memorable; easy to type then all the better.
// I find docker's approach at generating random container names very
// fit for the purpose and funny at the same time.

// As such the implementation of this script is an exact copy of docker's
// approach.
// reference: pkg/namesgenerator/names-generator.go

// Each generated name adheres to the form:
// {adjective}_{fictitious_name}

// Where {fictitious_name} is that of a fictional character from imaginary universes
// such as:
// Lord Of The Rings (LOTR)
// Star Wars (SW) - not included as of yet
// Harry Potter (HP) - not included as of yet

function randomNumber(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}

function generateRandomName() {

  const adjectives = [
    'admiring',
    'adoring',
    'affectionate',
    'agitated',
    'amazing',
    'angry',
    'awesome',
    'beautiful',
    'blissful',
    'bold',
    'boring',
    'brave',
    'busy',
    'charming',
    'clever',
    'cool',
    'compassionate',
    'competent',
    'condescending',
    'confident',
    'cranky',
    'crazy',
    'dazzling',
    'determined',
    'distracted',
    'dreamy',
    'eager',
    'ecstatic',
    'elastic',
    'elated',
    'elegant',
    'eloquent',
    'epic',
    'exciting',
    'fervent',
    'festive',
    'flamboyant',
    'focused',
    'friendly',
    'frosty',
    'funny',
    'gallant',
    'gifted',
    'goofy',
    'gracious',
    'great',
    'happy',
    'hardcore',
    'heuristic',
    'hopeful',
    'hungry',
    'infallible',
    'inspiring',
    'intelligent',
    'interesting',
    'jolly',
    'jovial',
    'keen',
    'kind',
    'laughing',
    'loving',
    'lucid',
    'magical',
    'mystifying',
    'modest',
    'musing',
    'naughty',
    'nervous',
    'nice',
    'nifty',
    'nostalgic',
    'objective',
    'optimistic',
    'peaceful',
    'pedantic',
    'pensive',
    'practical',
    'priceless',
    'quirky',
    'quizzical',
    'recursing',
    'relaxed',
    'reverent',
    'romantic',
    'sad',
    'serene',
    'sharp',
    'silly',
    'sleepy',
    'stoic',
    'strange',
    'stupefied',
    'suspicious',
    'sweet',
    'tender',
    'thirsty',
    'trusting',
    'unruffled',
    'upbeat',
    'vibrant',
    'vigilant',
    'vigorous',
    'wizardly',
    'wonderful',
    'xenodochial',
    'youthful',
    'zealous',
    'zen'
  ];

  const fictitious = [
    'Aragorn',
    'Arwen',
    'Balin',
    'Bard',
    'Beorn',
    'Beren',
    'Baggins',
    'Bilbo',
    'Boromor',
    'Celeborn',
    'Celebrimbor',
    'Denethor',
    'Earendil',
    'Elwing',
    'Elendil',
    'Elrond',
    'Eomer',
    'Eowyn',
    'Faramir',
    'Feanor',
    'Fingolfin',
    'Finrod',
    'Finwe',
    'Frodo',
    'Galadriel',
    'Gandalf',
    'Gilgalad',
    'Glorfindel',
    'Gimli',
    'Goldberry',
    'Gollum',
    'Grima',
    'Wormtongue',
    'Hurin',
    'Isildur',
    'Kili',
    'Legolas',
    'Luthien',
    'Maedhros',
    'Melian',
    'Merry',
    'Morgoth',
    'Pippin',
    'Radagast',
    'Samwise',
    'Saruman',
    'Sauron',
    'Shelob',
    'Smaug',
    'Smeagol',
    'Theoden',
    'Thingol',
    'Thranduil',
    'Thorin',
    'Tom',
    'Treebeard',
    'Tuor',
    'Idril',
    'Turin',
    'Ungoliant',
  ];

  return `${adjectives[randomNumber(0, adjectives.length)]}_${fictitious[randomNumber(0, fictitious.length)]}`
}

export { generateRandomName };
