* About
This file acts as a journal or notepad towards the goal of assisting the
development of af_admin.
* Core Agent Factory State Machine
** About
The agent factory state machine implements a hierarchical finite state machine.
Meaning it is a state machine composed of state machines.

** file structure
** Events
** Initializing the state machine
*** About
The Agent Factory State Machine is complicated.
It depends on various services in order to perform its function.

Many of its services are asynchronous.

The database service is asynchronous.
The Mqtt client service is asynchronous.
Retrieving the cached data if any is also asynchronous.


Most database and mqtt clients such as mongoose and mqtt.js implement the
EventEmitter interface.

some actions of the AFM are dependent upon their services.


*** Options
*** cached data
My state machine should have the ability to be provided with its initial state.
Both for testing purposes and because it is a requirement.
*** Store
*** Mqtt Client
*** Logger
** Persisting the state machine
** Some transitions are asynchronous
*** Implementing transitions as a promise
*** promises

States:
pending
fulfilled
rejected
settled

*** then
then(optional fn onFulfilled, optional fn onRejected)

returns synchronously a promise

** Handling the stores asynchronous initializiation
*** Local initialization check
*** Delayed startup
*** pre initialization queues
