* Material UI
** Container
** Box
** sx
* Localizing the app
** Resources
https://developer.mozilla.org/en-US/docs/Glossary/Locale
** Detect the user's locale
https://stackoverflow.com/questions/673905/how-to-determine-users-locale-within-browser

The stack overflow article suggests that the most reliable method for detecting a user's prefered language is
to read the <Accept-Language> Http header.

However MDN supports that newer browser versions offer the same functionality.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

** Translate typography elements
** Server locale-specific content such as dates, currencies and numbers
- Dates
    - Day names
    - Day name format
    - Month names
    - Month name format
    - Time format
- Currencies
    - Value
    - Symbol
- Numbers
    - Decimal points

** Flow
Enter Site -> (detect users locale) -> (store the locale to be offered, in a Cookie or somehing) -> render app

Attach listener to browser settings change
Fire event when user clicks on locale offered

User selects another language -> (store the locale to be offerd, in a Cookie or something) -> render app
User changes his language settings through the browser -> (store the locale to be offered, in a Cookie or something) -> render app
* State persistance
** resources
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
** Local && Session Storage
Setting local storage:
Window.localStorage.setting = "string"
Window.localStorage['setting'] = "string"
Window.localStorage.setItem('setting') = 'string'

Retreiving local storage:
Window.localStorage.setting
Window.localStorage['setting']
Window.localStorage.getItem('setting')

Window.localStorage value is a storage object
Window.sessionStorage value is a storage object
THeir difference is their expiration date. The localStorage storage object persists across even system reboots.
The sessionStorage object does not persist even across browser sessions.

Responding to storage changes with the StorageEvent:
the StorageEvent is fired whenever a change is made to the Storage object.


** Cookies
* Session implementation
* Mqtt
An mqtt client is a message delivery agent.

A responsible mqtt client *must* provide such facilities as to be able to bring
forth *accurate*, *definitive* and *up to date* information about the state of a
message.

** Questions
If an mqtt exchange operates in blocking and non-blocking mode (synchronous and
asynchronous) which facilities does npm/mqtt offer for selecting between the 2?

** Glossary
*** Payload
A payload is the client's data admitted for distribution. The term excludes the
data added by the broker.
*** Message
A message is comprised of the payload, the topic and any other information added
by the broker.
*** Topic
A topic is an address of channel.
*** Broker
A broker is relatively equivalent to a server in the mqtt universe.
It is responsible for:

Enabling publishers.
Admitting subscribers.
Making sure to forward messages to their registered channel.
*** Publisher
A client to the broker, who has submitted a payload for distribution to the
network.
*** Subscriber
A client to the broker, who has registered an interest in collecting published
payloads.




** My Client
this.server._subscibe -> asynchronous
this.server._publish -> asynchronous

* Color pallete
** purple
#+begin_src css
  /* BLACK */
  #000000

  /* WHITE */
  #ffffff

  /* PURPLE */
  #f3e5f5
  #e1bee7
  #ce93d8
  #ba68c8
  #ab47bc
  #9c27b0
  #8e24aa
  #7b1fa2
  #6a1b9a
  #4a148c
  #ea80fc
  #e040fb
  #d500f9
  #aa00ff


  #f2f0fc
  #cbc1ff
  #b2a3ff
  #a18fff
  #8476d1
  #6753ac
  #40199a
  #1f0066

  /* DEEP PURPLE */
  #ede7f6
  #d1c4e9
  #b39ddb
  #9575cd
  #7e57c2
  #673ab7
  #5e35b1
  #512da8
  #4527a0
  #311b92
  #b388ff
  #7c4dff
  #651fff
  #6200ea

  /* GREY */
  #FFF
  #f9f9f9
  #f0f0f0
  #e8e8e8
  #dfdfdf
  #d7d7d7
  #cecece
  #c6c6c6
  #bdbdbd
  #b4b4b4
  #acacac
  #a3a3a3
  #9b9b9b
  #939393
  #8a8a8a
  #828282
  #797979


  /* AF ADMIN */
  base: #d199ff
  shade: #c988ff
  shade: #c277ff
  shade: #ba66ff
  shade: #b255ff

  #9F34F7
  #793BAB
  #9F34F7
  #793BAB
  #793BAB
  #9F34F7

  /* 3 Main colors */
  /* 60% */ #d199FF hsl(273, 100%, 80%)
  /* 30% */ #FF92DE hsl(318, 100%, 79%)
  /* 30% */ #AEA0FF hsl(249, 100%, 81%)

  
#+end_src
